// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	KeyHash    string             `json:"key_hash"`
	Label      *string            `json:"label"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type AuthUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type DatasetsIngestionRun struct {
	ID              pgtype.UUID        `json:"id"`
	SourceKey       string             `json:"source_key"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Status          string             `json:"status"`
	RecordsFetched  int32              `json:"records_fetched"`
	RecordsInserted int32              `json:"records_inserted"`
	RecordsSkipped  int32              `json:"records_skipped"`
	ErrorMessage    *string            `json:"error_message"`
	Parameters      []byte             `json:"parameters"`
}

type DatasetsRawEvent struct {
	ID             pgtype.UUID        `json:"id"`
	SourceKey      string             `json:"source_key"`
	ExternalID     string             `json:"external_id"`
	FipsCode       *string            `json:"fips_code"`
	EventType      string             `json:"event_type"`
	EventSubtype   *string            `json:"event_subtype"`
	Severity       *string            `json:"severity"`
	EventStart     pgtype.Timestamptz `json:"event_start"`
	EventEnd       pgtype.Timestamptz `json:"event_end"`
	RawData        []byte             `json:"raw_data"`
	IngestionRunID pgtype.UUID        `json:"ingestion_run_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DatasetsSource struct {
	SourceKey   string             `json:"source_key"`
	DisplayName string             `json:"display_name"`
	BaseUrl     *string            `json:"base_url"`
	Description *string            `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GeographyCounty struct {
	FipsCode              string             `json:"fips_code"`
	CountyName            string             `json:"county_name"`
	StateFips             string             `json:"state_fips"`
	StateName             string             `json:"state_name"`
	StateAbbr             string             `json:"state_abbr"`
	Population            *int32             `json:"population"`
	AreaSqKm              pgtype.Numeric     `json:"area_sq_km"`
	Lat                   pgtype.Numeric     `json:"lat"`
	Lon                   pgtype.Numeric     `json:"lon"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	MedianHouseholdIncome *int32             `json:"median_household_income"`
}

type PrioritizationRanking struct {
	ID             pgtype.UUID        `json:"id"`
	RankingDate    pgtype.Date        `json:"ranking_date"`
	ModelVersionID pgtype.UUID        `json:"model_version_id"`
	GeneratedAt    pgtype.Timestamptz `json:"generated_at"`
}

type PrioritizationRankingEntry struct {
	ID                pgtype.UUID `json:"id"`
	RankingID         pgtype.UUID `json:"ranking_id"`
	FipsCode          string      `json:"fips_code"`
	Rank              int32       `json:"rank"`
	RiskScoreID       pgtype.UUID `json:"risk_score_id"`
	RecommendedAction *string     `json:"recommended_action"`
	ActionPriority    *string     `json:"action_priority"`
}

type RiskCountyFeature struct {
	ID                     pgtype.UUID        `json:"id"`
	FipsCode               string             `json:"fips_code"`
	FeatureDate            pgtype.Date        `json:"feature_date"`
	WindowDays             int32              `json:"window_days"`
	DisasterCount          int32              `json:"disaster_count"`
	MajorDisasterCount     int32              `json:"major_disaster_count"`
	SevereWeatherCount     int32              `json:"severe_weather_count"`
	EarthquakeCount        int32              `json:"earthquake_count"`
	MaxEarthquakeMagnitude pgtype.Numeric     `json:"max_earthquake_magnitude"`
	PopulationExposure     pgtype.Numeric     `json:"population_exposure"`
	HazardFrequencyScore   pgtype.Numeric     `json:"hazard_frequency_score"`
	Features               []byte             `json:"features"`
	ComputedAt             pgtype.Timestamptz `json:"computed_at"`
	EconomicExposure       pgtype.Numeric     `json:"economic_exposure"`
	LogPopulation          pgtype.Numeric     `json:"log_population"`
	IncomeVulnerability    pgtype.Numeric     `json:"income_vulnerability"`
}

type RiskModelVersion struct {
	ID             pgtype.UUID        `json:"id"`
	ModelName      string             `json:"model_name"`
	ModelType      string             `json:"model_type"`
	Version        string             `json:"version"`
	TrainedAt      pgtype.Timestamptz `json:"trained_at"`
	FeatureColumns []string           `json:"feature_columns"`
	Metrics        []byte             `json:"metrics"`
	ArtifactPath   *string            `json:"artifact_path"`
	Active         bool               `json:"active"`
	Notes          *string            `json:"notes"`
}

type RiskScore struct {
	ID              pgtype.UUID        `json:"id"`
	FipsCode        string             `json:"fips_code"`
	ModelVersionID  pgtype.UUID        `json:"model_version_id"`
	ScoreDate       pgtype.Date        `json:"score_date"`
	RiskScore       pgtype.Numeric     `json:"risk_score"`
	RiskLevel       string             `json:"risk_level"`
	ConfidenceLower pgtype.Numeric     `json:"confidence_lower"`
	ConfidenceUpper pgtype.Numeric     `json:"confidence_upper"`
	TopDrivers      []byte             `json:"top_drivers"`
	ComputedAt      pgtype.Timestamptz `json:"computed_at"`
	ClusterID       *int16             `json:"cluster_id"`
	ClusterLabel    *string            `json:"cluster_label"`
}

type ScenariosDefinition struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedBy   *string            `json:"created_by"`
	Parameters  []byte             `json:"parameters"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ScenariosResult struct {
	ID                 pgtype.UUID        `json:"id"`
	ScenarioID         pgtype.UUID        `json:"scenario_id"`
	FipsCode           string             `json:"fips_code"`
	SimulatedRiskScore pgtype.Numeric     `json:"simulated_risk_score"`
	SimulatedRiskLevel *string            `json:"simulated_risk_level"`
	DeltaFromBaseline  pgtype.Numeric     `json:"delta_from_baseline"`
	TopDrivers         []byte             `json:"top_drivers"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}
