// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: risk.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCountyHistory = `-- name: GetCountyHistory :many
SELECT score_date, risk_score, risk_level
FROM risk.scores s
JOIN risk.model_versions mv ON mv.id = s.model_version_id
WHERE s.fips_code = $1
  AND mv.active = true
ORDER BY score_date ASC
LIMIT 90
`

type GetCountyHistoryRow struct {
	ScoreDate  pgtype.Date    `json:"score_date"`
	RiskScore  pgtype.Numeric `json:"risk_score"`
	RiskLevel  string         `json:"risk_level"`
}

func (q *Queries) GetCountyHistory(ctx context.Context, fipsCode string) ([]GetCountyHistoryRow, error) {
	rows, err := q.db.Query(ctx, getCountyHistory, fipsCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountyHistoryRow
	for rows.Next() {
		var i GetCountyHistoryRow
		if err := rows.Scan(&i.ScoreDate, &i.RiskScore, &i.RiskLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countRankings = `-- name: CountRankings :one
SELECT COUNT(*)::int AS total
FROM risk.scores s
JOIN risk.model_versions mv ON mv.id = s.model_version_id
WHERE mv.active = true
  AND s.score_date = (SELECT MAX(score_date) FROM risk.scores WHERE model_version_id = mv.id)
`

func (q *Queries) CountRankings(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRankings)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getCountyFeatures = `-- name: GetCountyFeatures :one
SELECT
    f.fips_code,
    disaster_count,
    major_disaster_count,
    severe_weather_count,
    earthquake_count,
    max_earthquake_magnitude,
    population_exposure,
    hazard_frequency_score,
    economic_exposure,
    feature_date
FROM risk.county_features f
WHERE f.fips_code = $1
  AND f.feature_date = (SELECT MAX(feature_date) FROM risk.county_features WHERE fips_code = $1)
  AND f.window_days = 90
`

type GetCountyFeaturesRow struct {
	FipsCode               string         `json:"fips_code"`
	DisasterCount          int32          `json:"disaster_count"`
	MajorDisasterCount     int32          `json:"major_disaster_count"`
	SevereWeatherCount     int32          `json:"severe_weather_count"`
	EarthquakeCount        int32          `json:"earthquake_count"`
	MaxEarthquakeMagnitude pgtype.Numeric `json:"max_earthquake_magnitude"`
	PopulationExposure     pgtype.Numeric `json:"population_exposure"`
	HazardFrequencyScore   pgtype.Numeric `json:"hazard_frequency_score"`
	EconomicExposure       pgtype.Numeric `json:"economic_exposure"`
	FeatureDate            pgtype.Date    `json:"feature_date"`
}

func (q *Queries) GetCountyFeatures(ctx context.Context, fipsCode string) (GetCountyFeaturesRow, error) {
	row := q.db.QueryRow(ctx, getCountyFeatures, fipsCode)
	var i GetCountyFeaturesRow
	err := row.Scan(
		&i.FipsCode,
		&i.DisasterCount,
		&i.MajorDisasterCount,
		&i.SevereWeatherCount,
		&i.EarthquakeCount,
		&i.MaxEarthquakeMagnitude,
		&i.PopulationExposure,
		&i.HazardFrequencyScore,
		&i.EconomicExposure,
		&i.FeatureDate,
	)
	return i, err
}

const getCountyScore = `-- name: GetCountyScore :one
SELECT
    s.fips_code,
    c.county_name,
    c.state_name,
    c.state_abbr,
    c.population,
    c.median_household_income,
    s.risk_score,
    s.risk_level,
    s.top_drivers,
    s.score_date
FROM risk.scores s
JOIN geography.counties c USING (fips_code)
JOIN risk.model_versions mv ON mv.id = s.model_version_id
WHERE s.fips_code = $1
  AND mv.active = true
  AND s.score_date = (SELECT MAX(score_date) FROM risk.scores WHERE model_version_id = mv.id)
`

type GetCountyScoreRow struct {
	FipsCode               string         `json:"fips_code"`
	CountyName             string         `json:"county_name"`
	StateName              string         `json:"state_name"`
	StateAbbr              string         `json:"state_abbr"`
	Population             *int32         `json:"population"`
	MedianHouseholdIncome  *int32         `json:"median_household_income"`
	RiskScore              pgtype.Numeric `json:"risk_score"`
	RiskLevel              string         `json:"risk_level"`
	TopDrivers             []byte         `json:"top_drivers"`
	ScoreDate              pgtype.Date    `json:"score_date"`
}

func (q *Queries) GetCountyScore(ctx context.Context, fipsCode string) (GetCountyScoreRow, error) {
	row := q.db.QueryRow(ctx, getCountyScore, fipsCode)
	var i GetCountyScoreRow
	err := row.Scan(
		&i.FipsCode,
		&i.CountyName,
		&i.StateName,
		&i.StateAbbr,
		&i.Population,
		&i.MedianHouseholdIncome,
		&i.RiskScore,
		&i.RiskLevel,
		&i.TopDrivers,
		&i.ScoreDate,
	)
	return i, err
}

const getRankings = `-- name: GetRankings :many
SELECT
    ROW_NUMBER() OVER (ORDER BY s.risk_score DESC)::int AS rank,
    s.fips_code,
    c.county_name,
    c.state_abbr,
    c.population,
    s.risk_score,
    s.risk_level,
    s.top_drivers,
    s.score_date
FROM risk.scores s
JOIN geography.counties c USING (fips_code)
JOIN risk.model_versions mv ON mv.id = s.model_version_id
WHERE mv.active = true
  AND s.score_date = (SELECT MAX(score_date) FROM risk.scores WHERE model_version_id = mv.id)
ORDER BY s.risk_score DESC
LIMIT $1 OFFSET $2
`

type GetRankingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRankingsRow struct {
	Rank       int32          `json:"rank"`
	FipsCode   string         `json:"fips_code"`
	CountyName string         `json:"county_name"`
	StateAbbr  string         `json:"state_abbr"`
	Population *int32         `json:"population"`
	RiskScore  pgtype.Numeric `json:"risk_score"`
	RiskLevel  string         `json:"risk_level"`
	TopDrivers []byte         `json:"top_drivers"`
	ScoreDate  pgtype.Date    `json:"score_date"`
}

func (q *Queries) GetRankings(ctx context.Context, arg GetRankingsParams) ([]GetRankingsRow, error) {
	rows, err := q.db.Query(ctx, getRankings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankingsRow
	for rows.Next() {
		var i GetRankingsRow
		if err := rows.Scan(
			&i.Rank,
			&i.FipsCode,
			&i.CountyName,
			&i.StateAbbr,
			&i.Population,
			&i.RiskScore,
			&i.RiskLevel,
			&i.TopDrivers,
			&i.ScoreDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskSummary = `-- name: GetRiskSummary :many
SELECT
    s.risk_level,
    COUNT(*)::int AS county_count
FROM risk.scores s
JOIN risk.model_versions mv ON mv.id = s.model_version_id
WHERE mv.active = true
  AND s.score_date = (SELECT MAX(score_date) FROM risk.scores WHERE model_version_id = mv.id)
GROUP BY s.risk_level
`

type GetRiskSummaryRow struct {
	RiskLevel   string `json:"risk_level"`
	CountyCount int32  `json:"county_count"`
}

func (q *Queries) GetRiskSummary(ctx context.Context) ([]GetRiskSummaryRow, error) {
	rows, err := q.db.Query(ctx, getRiskSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRiskSummaryRow
	for rows.Next() {
		var i GetRiskSummaryRow
		if err := rows.Scan(&i.RiskLevel, &i.CountyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
