// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scenarios.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios.definitions (name, description, created_by, parameters)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, parameters, created_at
`

type CreateScenarioParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedBy   *string `json:"created_by"`
	Parameters  []byte  `json:"parameters"`
}

type CreateScenarioRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Parameters  []byte             `json:"parameters"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.Parameters,
	)
	var i CreateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.CreatedAt,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, name, description, parameters, created_at
FROM scenarios.definitions
WHERE id = $1
`

type GetScenarioRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Parameters  []byte             `json:"parameters"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetScenario(ctx context.Context, id pgtype.UUID) (GetScenarioRow, error) {
	row := q.db.QueryRow(ctx, getScenario, id)
	var i GetScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Parameters,
		&i.CreatedAt,
	)
	return i, err
}

const getScenarioResults = `-- name: GetScenarioResults :many
SELECT
    r.fips_code,
    c.county_name,
    c.state_abbr,
    r.simulated_risk_score,
    r.simulated_risk_level,
    r.delta_from_baseline,
    r.top_drivers
FROM scenarios.results r
JOIN geography.counties c USING (fips_code)
WHERE r.scenario_id = $1
ORDER BY r.simulated_risk_score DESC NULLS LAST
`

type GetScenarioResultsRow struct {
	FipsCode           string         `json:"fips_code"`
	CountyName         string         `json:"county_name"`
	StateAbbr          string         `json:"state_abbr"`
	SimulatedRiskScore pgtype.Numeric `json:"simulated_risk_score"`
	SimulatedRiskLevel *string        `json:"simulated_risk_level"`
	DeltaFromBaseline  pgtype.Numeric `json:"delta_from_baseline"`
	TopDrivers         []byte         `json:"top_drivers"`
}

func (q *Queries) GetScenarioResults(ctx context.Context, scenarioID pgtype.UUID) ([]GetScenarioResultsRow, error) {
	rows, err := q.db.Query(ctx, getScenarioResults, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScenarioResultsRow
	for rows.Next() {
		var i GetScenarioResultsRow
		if err := rows.Scan(
			&i.FipsCode,
			&i.CountyName,
			&i.StateAbbr,
			&i.SimulatedRiskScore,
			&i.SimulatedRiskLevel,
			&i.DeltaFromBaseline,
			&i.TopDrivers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, name, description, parameters, created_at
FROM scenarios.definitions
ORDER BY created_at DESC
`

type ListScenariosRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Parameters  []byte             `json:"parameters"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListScenarios(ctx context.Context) ([]ListScenariosRow, error) {
	rows, err := q.db.Query(ctx, listScenarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosRow
	for rows.Next() {
		var i ListScenariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Parameters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScenarioResult = `-- name: UpsertScenarioResult :exec
INSERT INTO scenarios.results (
    scenario_id, fips_code, simulated_risk_score,
    simulated_risk_level, delta_from_baseline, top_drivers
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scenario_id, fips_code) DO UPDATE SET
    simulated_risk_score  = EXCLUDED.simulated_risk_score,
    simulated_risk_level  = EXCLUDED.simulated_risk_level,
    delta_from_baseline   = EXCLUDED.delta_from_baseline,
    top_drivers           = EXCLUDED.top_drivers,
    computed_at           = now()
`

type UpsertScenarioResultParams struct {
	ScenarioID         pgtype.UUID    `json:"scenario_id"`
	FipsCode           string         `json:"fips_code"`
	SimulatedRiskScore pgtype.Numeric `json:"simulated_risk_score"`
	SimulatedRiskLevel *string        `json:"simulated_risk_level"`
	DeltaFromBaseline  pgtype.Numeric `json:"delta_from_baseline"`
	TopDrivers         []byte         `json:"top_drivers"`
}

func (q *Queries) UpsertScenarioResult(ctx context.Context, arg UpsertScenarioResultParams) error {
	_, err := q.db.Exec(ctx, upsertScenarioResult,
		arg.ScenarioID,
		arg.FipsCode,
		arg.SimulatedRiskScore,
		arg.SimulatedRiskLevel,
		arg.DeltaFromBaseline,
		arg.TopDrivers,
	)
	return err
}
